applicationName: IntegrationTestNotebooksIdC
content:
  storage:
  - name: notebooks
    include:
    - notebooks/
    exclude:
    - .ipynb_checkpoints/
    - __pycache__/
  - name: workflows
    include:
    - workflows/
  workflows:
  - workflowName: notebooks_workflow
    connectionName: default.workflow_serverless
stages:
  test-idc:
    stage: TEST
    domain:
      name: smus-idc-test-domain
      region: ${TEST_DOMAIN_REGION}
    project:
      name: test-marketing
      owners:
      - arn:aws:iam::${AWS_ACCOUNT_ID}:role/GitHubActionsRole-SMUS-CLI-Tests
      - arn:aws:iam::${AWS_ACCOUNT_ID}:role/Admin
    environment_variables:
      S3_PREFIX: test
    deployment_configuration:
      storage:
      - name: notebooks
        connectionName: default.s3_shared
        targetDirectory: notebooks/bundle/notebooks
      - name: workflows
        connectionName: default.s3_shared
        targetDirectory: notebooks/bundle/workflows
    bootstrap:
      actions:
      - type: datazone.create_connection
        name: mlflow-server
        connection_type: MLFLOW
        properties:
          trackingServerArn: arn:aws:sagemaker:${TEST_DOMAIN_REGION}:${AWS_ACCOUNT_ID}:mlflow-tracking-server/${MLFLOW_TRACKING_SERVER_NAME:smus-integration-mlflow-use1}
      - type: datazone.create_connection
        name: default.spark
        connection_type: SPARK_GLUE
        properties:
          glue_version: "5.0"
          worker_type: G.1X
          num_workers: 10
      - type: workflow.create
        workflowName: notebooks_workflow
      - type: workflow.run
        workflowName: notebooks_workflow
        trailLogs: true
tests:
  folder: examples/analytic-workflow/data-notebooks/app_tests/
