applicationName: DemoMarketingBundle
content: {}
stages:
  dev:
    stage: DEV
    domain:
      region: ${DEV_DOMAIN_REGION:us-east-1}
    project:
      name: dev-project-name
      create: false
  test:
    stage: TEST
    domain:
      region: ${DEV_DOMAIN_REGION:us-east-1}
    project:
      name: test-project-name
  prod:
    stage: PROD
    domain:
      region: ${DEV_DOMAIN_REGION:us-east-1}
    project:
      name: prod-project-name
