"""
Validation tests for catalog import/export deployment.

These tests verify that catalog resources exist in the target project
after a deploy, and check publish status based on source listing state.

Tests use the smus_config fixture which is auto-generated by the
`smus-cli test` command with project connection details.
"""

import boto3
import pytest


@pytest.fixture(scope="module")
def datazone_client(smus_config):
    """Create DataZone client for the target region."""
    return boto3.client("datazone", region_name=smus_config["region"])


@pytest.fixture(scope="module")
def domain_id(smus_config):
    """Get the domain ID from test config."""
    return smus_config["domain_id"]


@pytest.fixture(scope="module")
def project_id(smus_config):
    """Get the project ID from test config."""
    return smus_config["project_id"]


def _search_resources(client, domain_id, project_id, search_scope, max_results=50):
    """Search for catalog resources in the project."""
    try:
        resp = client.search(
            domainIdentifier=domain_id,
            owningProjectIdentifier=project_id,
            searchScope=search_scope,
            maxResults=max_results,
        )
        return resp.get("items", [])
    except Exception as e:
        pytest.skip(f"Could not search {search_scope}: {e}")
        return []


def test_glossaries_exist(datazone_client, domain_id, project_id):
    """Verify that glossaries were imported into the target project."""
    items = _search_resources(datazone_client, domain_id, project_id, "GLOSSARY")
    assert len(items) > 0, "No glossaries found in target project"
    print(f"✅ Found {len(items)} glossary(ies) in target project")


def test_glossary_terms_exist(datazone_client, domain_id, project_id):
    """Verify that glossary terms were imported into the target project."""
    items = _search_resources(datazone_client, domain_id, project_id, "GLOSSARY_TERM")
    assert len(items) > 0, "No glossary terms found in target project"
    print(f"✅ Found {len(items)} glossary term(s) in target project")


def test_assets_exist(datazone_client, domain_id, project_id):
    """Verify that assets were imported into the target project."""
    items = _search_resources(datazone_client, domain_id, project_id, "ASSET")
    assert len(items) > 0, "No assets found in target project"
    print(f"✅ Found {len(items)} asset(s) in target project")


def _find_bundle_zip():
    """Find the most recent bundle ZIP containing catalog_export.json."""
    import glob
    import os

    search_dirs = [
        ".",
        "..",
        os.path.join("..", ".."),
        os.path.join("..", "..", "artifacts"),
        "artifacts",
    ]
    candidates = []
    for d in search_dirs:
        candidates.extend(glob.glob(os.path.join(d, "*.zip")))
    # Return the most recently modified ZIP that contains catalog data
    for zip_path in sorted(candidates, key=os.path.getmtime, reverse=True):
        try:
            import zipfile

            with zipfile.ZipFile(zip_path, "r") as zf:
                if "catalog/catalog_export.json" in zf.namelist():
                    return zip_path
        except Exception:
            continue
    return None


def _load_catalog_export():
    """Load the full catalog_export.json from the bundle ZIP."""
    import json
    import zipfile

    zip_path = _find_bundle_zip()
    if not zip_path:
        return None
    with zipfile.ZipFile(zip_path, "r") as zf:
        with zf.open("catalog/catalog_export.json") as f:
            return json.load(f)


def test_asset_names_match(datazone_client, domain_id, project_id):
    """Verify that asset names in the target project match those from the bundle."""
    catalog_data = _load_catalog_export()
    if catalog_data is None:
        pytest.skip("No bundle ZIP with catalog_export.json found")

    expected_names = {a["name"] for a in catalog_data.get("assets", []) if "name" in a}
    if not expected_names:
        pytest.skip("No assets in catalog export to verify")

    items = _search_resources(datazone_client, domain_id, project_id, "ASSET")
    target_names = set()
    for item in items:
        asset_item = item.get("assetItem", item.get("assetListing", {}))
        name = asset_item.get("name", "")
        if name:
            target_names.add(name)

    missing = expected_names - target_names
    assert (
        not missing
    ), f"Assets from bundle missing in target project: {sorted(missing)}"
    print(
        f"✅ All {len(expected_names)} exported asset(s) found in target: "
        f"{', '.join(sorted(expected_names))}"
    )


def test_publish_status_when_enabled(datazone_client, domain_id, project_id):
    """Verify that assets published in source are published in target.

    Loads the bundle's catalog_export.json to find which assets had
    listingStatus ACTIVE in the source, then checks those assets have
    a listingId in the target project.
    """
    catalog_data = _load_catalog_export()
    if catalog_data is None:
        pytest.skip("No bundle ZIP with catalog_export.json found")

    # Find asset names that were published (ACTIVE) in the source
    source_published = {
        a["name"]
        for a in catalog_data.get("assets", [])
        if a.get("listingStatus") == "ACTIVE" and "name" in a
    }
    if not source_published:
        pytest.skip("No published assets in source bundle to verify")

    items = _search_resources(datazone_client, domain_id, project_id, "ASSET")
    if not items:
        pytest.fail("No assets found in target project")

    # Build map of target asset name -> listingId
    target_published = set()
    for item in items:
        asset_item = item.get("assetItem", item.get("assetListing", {}))
        name = asset_item.get("name", "")
        if name and asset_item.get("listingId"):
            target_published.add(name)

    missing = source_published - target_published
    assert (
        not missing
    ), f"Assets published in source but not published in target: {sorted(missing)}"
    print(
        f"✅ All {len(source_published)} source-published asset(s) "
        f"are published in target"
    )


def test_form_types_exist(datazone_client, domain_id, project_id):
    """Verify that custom form types from the bundle exist in the target project."""
    catalog_data = _load_catalog_export()
    if catalog_data is None:
        pytest.skip("No bundle ZIP with catalog_export.json found")

    expected_names = {
        ft["name"] for ft in catalog_data.get("formTypes", []) if "name" in ft
    }
    if not expected_names:
        pytest.skip("No custom form types in catalog export to verify")

    try:
        resp = datazone_client.search_types(
            domainIdentifier=domain_id,
            searchScope="FORM_TYPE",
            managed=False,
            maxResults=50,
        )
        items = resp.get("items", [])
        target_names = {
            item.get("formTypeItem", {}).get("name")
            for item in items
            if item.get("formTypeItem", {}).get("owningProjectId") == project_id
        }
        target_names.discard(None)
    except Exception as e:
        pytest.skip(f"Could not search form types: {e}")
        return

    missing = expected_names - target_names
    assert (
        not missing
    ), f"Form types from bundle missing in target project: {sorted(missing)}"
    print(f"✅ All {len(expected_names)} exported form type(s) found in target")
