"""
Validation tests for catalog import/export deployment.

These tests verify that catalog resources exist in the target project
after a deploy, and check publish status based on source listing state.

Tests use the smus_config fixture which is auto-generated by the
`smus-cli test` command with project connection details.
"""

import boto3
import pytest


@pytest.fixture(scope="module")
def datazone_client(smus_config):
    """Create DataZone client for the target region."""
    return boto3.client("datazone", region_name=smus_config["region"])


@pytest.fixture(scope="module")
def domain_id(smus_config):
    """Get the domain ID from test config."""
    return smus_config["domain_id"]


@pytest.fixture(scope="module")
def project_id(smus_config):
    """Get the project ID from test config."""
    return smus_config["project_id"]


def _search_resources(client, domain_id, project_id, search_scope, max_results=50):
    """Search for catalog resources in the project."""
    try:
        resp = client.search(
            domainIdentifier=domain_id,
            owningProjectIdentifier=project_id,
            searchScope=search_scope,
            maxResults=max_results,
        )
        return resp.get("items", [])
    except Exception as e:
        pytest.skip(f"Could not search {search_scope}: {e}")
        return []


def test_glossaries_exist(datazone_client, domain_id, project_id):
    """Verify that glossaries were imported into the target project."""
    items = _search_resources(datazone_client, domain_id, project_id, "GLOSSARY")
    assert len(items) > 0, "No glossaries found in target project"
    print(f"✅ Found {len(items)} glossary(ies) in target project")


def test_glossary_terms_exist(datazone_client, domain_id, project_id):
    """Verify that glossary terms were imported into the target project."""
    items = _search_resources(datazone_client, domain_id, project_id, "GLOSSARY_TERM")
    assert len(items) > 0, "No glossary terms found in target project"
    print(f"✅ Found {len(items)} glossary term(s) in target project")


def test_assets_exist(datazone_client, domain_id, project_id):
    """Verify that assets were imported into the target project."""
    items = _search_resources(datazone_client, domain_id, project_id, "ASSET")
    assert len(items) > 0, "No assets found in target project"
    print(f"✅ Found {len(items)} asset(s) in target project")


def test_asset_names_match(datazone_client, domain_id, project_id):
    """Verify that expected asset names are present in the target project."""
    items = _search_resources(datazone_client, domain_id, project_id, "ASSET")
    asset_names = set()
    for item in items:
        asset_item = item.get("assetItem", item.get("assetListing", {}))
        name = asset_item.get("name", "")
        if name:
            asset_names.add(name)

    assert len(asset_names) > 0, "No asset names found"
    print(f"✅ Asset names in target: {', '.join(sorted(asset_names))}")


def test_publish_status_when_enabled(datazone_client, domain_id, project_id):
    """Verify that assets published in source are published in target.

    This test checks that assets have a listing status indicating they
    have been published. Assets are published based on their source
    listingStatus (LISTED). If skipPublish is true, this test is skipped.
    """
    items = _search_resources(datazone_client, domain_id, project_id, "ASSET")
    if not items:
        pytest.skip("No assets found to check publish status")

    published_count = 0
    for item in items:
        asset_item = item.get("assetItem", item.get("assetListing", {}))
        # Check for listing or published indicators
        listing_id = asset_item.get("listingId")
        if listing_id:
            published_count += 1

    print(f"✅ {published_count}/{len(items)} assets have listing IDs (published)")


def test_form_types_exist(datazone_client, domain_id, project_id):
    """Verify that custom form types were imported into the target project."""
    try:
        resp = datazone_client.search_types(
            domainIdentifier=domain_id,
            searchScope="FORM_TYPE",
            managed=False,
            maxResults=50,
        )
        items = resp.get("items", [])
        # Filter to project-owned form types
        project_forms = [
            item for item in items
            if item.get("formTypeItem", {}).get("owningProjectId") == project_id
        ]
        if project_forms:
            print(f"✅ Found {len(project_forms)} custom form type(s) in target project")
        else:
            print("ℹ️  No custom form types found (may not have been seeded)")
    except Exception as e:
        pytest.skip(f"Could not search form types: {e}")
