name: Deploy Data Notebooks

on:
  push:
    branches:
      - main
      - test
      - amirbo_feature_branch
    paths:
      - 'examples/analytic-workflow/data-notebooks/**'
      - 'src/**'
      - '.github/workflows/smus-direct-deploy.yml'
      - '.github/workflows/analytic-data-notebooks.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/smus-direct-deploy.yml
    secrets:
      AWS_ROLE_ARN_TEST: ${{ secrets.AWS_ROLE_ARN_TEST }}
    with:
      manifest_path: 'examples/analytic-workflow/data-notebooks/manifest.yaml'
      test_target: 'test'

  deploy-idc:
    uses: ./.github/workflows/smus-direct-deploy.yml
    secrets:
      AWS_ROLE_ARN_TEST: ${{ secrets.AWS_ROLE_ARN_TEST }}
    with:
      manifest_path: 'examples/analytic-workflow/data-notebooks/manifest-idc.yaml'
      test_target: 'test-idc'
